### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [Borlea/OldEnchanting#1]

**Comment by Arnuh** [comment]
Can you give me the error log? As I am unable to reproduce the NPE

If you would like a fix for #2 here it is https://github.com/Borlea/OldEnchanting/releases/tag/1.0.1

**Comment by Aangiix3** [comment]
Thanks for the quick fix.
About #1, it tries to do a rand.nextInt(0) when there's 0 books around the enchantment-table so it throws an exception

**Comment by Aangiix3** [comment]
Will send the log tommorow as I'm mobile right now

**Comment by Aangiix3** [comment]
[Server thread/ERROR]: Could not pass event PrepareItemEnchantEvent to OldEnchanting v1.0.1
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51]

So yeah, it's the new Random().nextInt(0); when there's 0 books

**Comment by Borlea** [comment]
@Aangiix3 what line exactly?

**Comment by Arnuh** [comment]
You can get the fix [here](https://github.com/Borlea/OldEnchanting/releases/tag/1.0.1)

**Comment by Aangiix3** [comment]
It takes about 2 minutes to get a level 30 enchant
is there a way you could make it like in 1.7?

Players are getting tired of trying and retrying to get a level 30 enchant..
I thought about setting it to 30 when it's 29, but not sure that is a right "fix"
