### ISSUE TITLE
Need a bug fix, or update. OldEnchanting

### ISSUE THREAD

**Issue by ghost** [Borlea/OldEnchanting#3]
Hello! Well first of all, this is an awesome plugin, though it is small, it actually changes hugely the playability of your server, bringing more challenging to your comunity.
  The plugin works like a charm, though I've found 2 errors. The 1st one, and already known, the bug that was discussed in the first issue submitted here, that was about being able to see the enchantments names. This can be done whenever you put an item to enchant or even put lapis on the second spot, then you rapidly put your cursor on the enchantments and it shows you the name for about miliseconds until it hides again, but those miliseconds are enough to figure out the enchantment. It is a small bug, but it can be highly abused.
The 2nd bug is that if you disable "RandomizeEnchantments" on the config file, it makes no effect, and there is no way to disable that event though it works great, there may be people that prefers to not have randomized enchants each time someone put an item in the enchanting table. So it would be greatful if you could fix that node of the config.yml. 
  Other than that, I don't seem to find other errors on the plugin, If you fix those, it would become a perfect plugin in other words. At least for 1.8.X since I haven't tested it in newer versions.
  Great work anyways! 5 Stars :) Hope you the best.

**Comment by Arnuh** [comment]
The ability to see the enchantments isn't really possible to fix unless I dig more into how they calculate the enchants. The issue is Spigot doesn't expose the offers in the event until 1.11 so we have no way to change it instantly and must do some sort of delay.

Also I think 1.8 always had randomized enchants? That feature was added for later versions where the enchants wont change unless you grab a different item type(sword, pickaxe,etc) or enchant an item.

**Comment by ghost** [comment]
I'm very very sorry for this late reply, I haven't received any notification of github. 
  In 1.8.9, enchantments don't randomize. You have to enchant and item to refresh all the enchantments again. Also, when you activate the lapis cost, always when you put the lapis, it also randomize all the enchantments. I would really like if you could fix the randomized enchantments node since nothing happens even if you disable it.
 Thank you very much for reading and for the fast response!
